#!/usr/bin/env bash
# Install or refresh the recipe-runner Hermes skill from this repo.
# Idempotent — safe to re-run after git pull.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SKILL_DIR="${HERMES_RECIPE_RUNNER_SKILL_DIR:-${HOME}/.hermes/skills/productivity/recipe-runner}"
SITE_URL="${RECIPE_RUNNER_SITE_URL:-http://localhost:4000}"
ADDED_BY="${RECIPE_RUNNER_ADDED_BY:-You}"

mkdir -p "${SKILL_DIR}/references"

cp "${REPO_ROOT}/docs/SKILL.md" "${SKILL_DIR}/"

for f in "${REPO_ROOT}"/docs/*.md; do
  base="$(basename "$f")"
  [[ "${base}" == "SKILL.md" ]] && continue
  cp "$f" "${SKILL_DIR}/references/"
done

cp "${REPO_ROOT}/references/vision-extract-prompt.md" "${SKILL_DIR}/references/"

cat > "${SKILL_DIR}/references/local-config.md" <<EOF
# Generated by scripts/install-hermes-skill.sh — edit for your machine

repo_path: ${REPO_ROOT}
site_url: ${SITE_URL}
added_by: ${ADDED_BY}
venv_python: ${REPO_ROOT}/.venv/bin/python
build: ${REPO_ROOT}/.venv/bin/python site/build.py
EOF

echo "recipe-runner skill installed: ${SKILL_DIR}"
echo "repo_path=${REPO_ROOT}"
echo "Next: ensure venv exists (python3 -m venv .venv && .venv/bin/pip install -r site/requirements.txt)"
echo "Verify: skill_view(name='recipe-runner') or ls ${SKILL_DIR}/SKILL.md"